### PR TITLE
Add French langage

### PR DESCRIPTION
**Pull request by Elementtair**

### CODE REVIEW

**Comment by MioVisman** [comment]
Thank you!

**Comment by Elementtair** [comment]
Sorry ... the translation was pretty obvious and I did'nt take the time to test it.

It appear that choosing french just break the script:
There's an issue with the translation files, seems to be with common.po and admin_install.po but I can't see any error.

I get this one :

PHP OTHER_ERROR: File (fr/common.po) format error in ...\app\Core\Lang.php:[200]

Trace:

    ...\app\Core\Lang.php(144): ForkBB\Core\Lang->arrayFromStr(string)
    ...\app\Models\Page.php(44): ForkBB\Core\Lang->load(string)
    ...\app\Models\Pages\Admin.php(23): ForkBB\Models\Page->__construct(object{ForkBB\Core\Container})
    ...\app\Models\Pages\Admin\Install.php(41): ForkBB\Models\Pages\Admin->__construct(object{ForkBB\Core\Container})
    ...\app\Core\Container.php(121): ForkBB\Models\Pages\Admin\Install->__construct(object{ForkBB\Core\Container})
    ...\app\Controllers\Install.php(89): ForkBB\Core\Container->__get(string)
    ...\app\Core\Container.php(117): ForkBB\Controllers\Install->routing()
    ...\app\bootstrap.php(81): ForkBB\Core\Container->__get(string)
    ...\index.php(14): require(string)

and if i use the english common.po , this one 


PHP OTHER_ERROR: File (fr/admin_install.po) format error in ...\app\Core\Lang.php:[200]

Trace:

    ...\app\Core\Lang.php(144): ForkBB\Core\Lang->arrayFromStr(string)
    ...\app\Models\Pages\Admin\Install.php(44): ForkBB\Core\Lang->load(string)
    ...\app\Core\Container.php(121): ForkBB\Models\Pages\Admin\Install->__construct(object{ForkBB\Core\Container})
    ...\app\Controllers\Install.php(89): ForkBB\Core\Container->__get(string)
    ...\app\Core\Container.php(117): ForkBB\Controllers\Install->routing()
    ...\app\bootstrap.php(81): ForkBB\Core\Container->__get(string)
    ...\index.php(14): require(string)

**Comment by MioVisman** [comment]
Removed extra empty lines

**Comment by MioVisman** [comment]
I haven't done any tests yet. The code needs to be updated to the current revision.

**Comment by Elementtair** [comment]
Just tried and that seem to work !  Didn't thought about those extra lines ...

**Pull request merged**
